export const forestState = {
  mode: "forest",
  limit: 100,
  offset: 0,
  total: 0,
  samples: [],
  nearest: [],
  selectedSampleId: null,
  selectedDetail: null,
  importFiles: [],
  layers: {
    samples: null,
    nearest: null,
    selected: null,
    plot: null,
    aoi: null,
    hansen: null,
    sentinel: null,
  },
  visibility: {
    samples: true,
    nearest: true,
    plot: true,
    aoi: true,
    hansen: true,
    sentinel: true,
  },
  hansenLayer: "dominant_year",
  hansenOpacity: 0.72,
  includeHansenTreecover: false,
  includeBatchHansenTreecover: false,
  layerPanelCollapsed: false,
  debugEvents: [],
  mapDebugAttached: false,
  mapClickCandidates: [],
  mapSelectHandler: null,
  lastFallbackSelectAt: 0,
  sentinelSelectedSceneKeys: new Set(),
  sentinelExpandedDownloadKeys: new Set(),
  sentinelReviewDrafts: new Map(),
  sentinelReviewSavingIds: new Set(),
  activeSentinelPreview: null,
  sentinelImageIdQuery: "",
  compareOpen: false,
  compareView: "rgb",
  comparePreDownloadId: null,
  comparePostDownloadId: null,
  compareShowHansen: true,
  compareHansenOpacity: 0.68,
  compareMaps: {
    pre: null,
    post: null,
  },
  compareLayers: {
    preImage: null,
    postImage: null,
    preHansen: null,
    postHansen: null,
  },
  compareSyncing: false,
  hansenJobId: null,
  hansenJobSampleId: null,
  hansenJob: null,
  hansenTimer: null,
  hansenBatchJobId: null,
  hansenBatchTimer: null,
};
